services:
  - type: web
    name: cuemath-screener
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false